version: "3.4"
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: proofviewer
      POSTGRES_PASSWORD: proofviewerpassword
      POSTGRES_USER: proofviewer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - proofviewernet

  proofviewer:
    image: samdickinson/proof-viewer-server:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: proofviewer
      POSTGRES_PASSWORD: proofviewerpassword
      POSTGRES_USER: proofviewer
    volumes:
      - proof-files:/proofviewer/content
    networks:
      - proofviewernet
      - default
    ports:
      - 8090:8090
    healthcheck:
      test: ["CMD", "/docker-health-check", "-url=http://127.0.0.1:8090/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  proofviewernet:

volumes:
  db-data:
  proof-files:
